# Generated by Django 4.2.10 on 2024-02-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('Areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=100, verbose_name='Status')),
                ('descripcion_status', models.CharField(default='', max_length=255, verbose_name='Descripcion del Status')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
                'db_table': 'Status',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_expediente', models.CharField(default='', max_length=100, verbose_name='Numero de Expediente')),
                ('nombre_remitente', models.CharField(default='', max_length=100, verbose_name='Nombre del Remitente')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('plazo_para_responder', models.DateField(verbose_name='Plazo para Responder')),
                ('numero_copias', models.IntegerField(default=0, verbose_name='Numero de Copias')),
                ('numero_anexos', models.IntegerField(default=0, verbose_name='Numero de Anexos')),
                ('fecha_de_cierre', models.DateField(verbose_name='Fecha de Cierre')),
                ('monto', models.FloatField(verbose_name='Monto')),
                ('abogado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='user_id')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Areas.departamento', verbose_name='area_id')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedientes.status', verbose_name='status_id')),
            ],
            options={
                'verbose_name': 'Expediente',
                'verbose_name_plural': 'Expedientes',
                'db_table': 'Expedientes',
                'ordering': ('id',),
            },
        ),
    ]
