# Generated by Django 4.2.10 on 2024-03-03 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_expediente_abogado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='abogado',
        ),
    ]
