# Generated by Django 4.2.10 on 2024-02-23 02:17

import Apps.documents.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
        ('Areas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_documento', models.CharField(max_length=255, verbose_name='Nombre del documento')),
                ('nombre_de_quien_entrega', models.CharField(max_length=100, verbose_name='Nombre de quien entrega')),
                ('status_delete', models.BooleanField(default=False, verbose_name='status')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('archivo', models.FileField(null=True, upload_to='media/archivos/', validators=[Apps.documents.models.validar_archivo_extension])),
                ('nombre_de_quien_carga', models.CharField(max_length=100, verbose_name='Nombre de quien carga')),
                ('expediente', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='expedientes.expediente')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'Document',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Tipo_Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tipo_Documento')),
                ('description', models.CharField(max_length=555, null=True, verbose_name='Descripcion')),
            ],
            options={
                'verbose_name': 'Tipo_Documento',
                'verbose_name_plural': 'Tipo_Documentos',
                'db_table': 'Tipo_Documento',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='sharedlinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urldocumento', models.CharField(default='', max_length=255, verbose_name='Url Documento')),
                ('linked_document', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='documents.document', verbose_name='Documento Vinculado')),
            ],
            options={
                'verbose_name': 'sharedlinks',
                'verbose_name_plural': 'sharedlinks',
                'db_table': 'sharedlinks',
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tipoDocumento',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tipo_Documento', to='documents.tipo_documento'),
        ),
        migrations.CreateModel(
            name='DocDep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='DocDep')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Departamento', to='Areas.departamento')),
                ('subdepartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subdepartamento', to='Areas.subdepartamento')),
            ],
            options={
                'verbose_name': 'DocDep',
                'verbose_name_plural': 'DocDeps',
                'db_table': 'DocDep',
                'ordering': ('id',),
            },
        ),
    ]
