# Generated by Django 4.2.10 on 2024-02-23 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Description')),
                ('isSuperAdmin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
                ('host', models.CharField(default='', max_length=100, null=True, verbose_name='Host access')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150, null=True, verbose_name='name')),
                ('last_name', models.CharField(default='', max_length=150, null=True, verbose_name='last name')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='email')),
                ('phone', models.CharField(default='', max_length=20, null=True, verbose_name='phone')),
                ('role', models.ForeignKey(choices=[(1, 'Administrador'), (2, 'Abogado'), (3, 'Supervisor'), (4, 'Auxiliar')], default='', on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ('id',),
            },
        ),
    ]
