# Generated by Django 4.2.10 on 2024-03-03 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loginregister_remove_user_role_delete_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginregister',
            name='usuario',
        ),
    ]
