# Generated by Django 4.2.10 on 2024-03-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_role_user_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivitiesRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cambio', models.CharField(max_length=200)),
            ],
        ),
    ]
