# Generated by Django 4.2.10 on 2024-03-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_loginregister_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginregister',
            old_name='login',
            new_name='login_time',
        ),
    ]
