# Generated by Django 4.2.10 on 2024-03-18 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_activitiesregister'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='role_id',
            new_name='role',
        ),
    ]
