# Generated by Django 4.2.10 on 2024-03-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_loginregister_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('description', models.CharField(default='', max_length=255, verbose_name='Description')),
                ('isSuperAdmin', models.BooleanField(default=False, verbose_name='Administrador')),
                ('status_delete', models.BooleanField(default=False, verbose_name='Status Delete')),
                ('host', models.CharField(default='', max_length=100, null=True, verbose_name='Host access')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'role',
                'ordering': ('id',),
            },
        ),
    ]
