# Generated by Django 4.2.10 on 2024-03-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='username',
        ),
    ]
