# Generated by Django 4.2.10 on 2024-03-03 07:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0008_rename_name_usuario_username'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('id',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='lastname',
        ),
        migrations.AddField(
            model_name='usuario',
            name='birthdate',
            field=models.DateField(null=True, verbose_name='birthdate'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='hidden_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='usuario',
            name='mothers_maiden_name',
            field=models.CharField(max_length=150, null=True, verbose_name='mother maiden name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='paternal_surname',
            field=models.CharField(max_length=150, null=True, verbose_name='paternal surname'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='phone',
            field=models.CharField(max_length=13, null=True, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='user',
        ),
    ]
