# Generated by Django 4.2.10 on 2024-03-03 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0010_role_groups_role_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='role',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='usuarios_related', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuarios_related', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
