# Generated by Django 4.2.10 on 2024-03-03 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_role_groups_remove_role_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ('id',), 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='hidden_fields',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='mothers_maiden_name',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='paternal_surname',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='phone',
        ),
        migrations.AddField(
            model_name='usuario',
            name='lastname',
            field=models.CharField(max_length=150, null=True, verbose_name='lastname'),
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
