# Generated by Django 4.2.10 on 2024-03-03 20:30

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0006_alter_expediente_abogado'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0012_alter_usuario_options_remove_usuario_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(default='', max_length=150, null=True, verbose_name='name')),
                ('last_name', models.CharField(default='', max_length=150, null=True, verbose_name='last name')),
                ('email', models.EmailField(default='', max_length=100, unique=True, verbose_name='email')),
                ('phone', models.CharField(default='', max_length=20, null=True, verbose_name='phone')),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('status_delete', models.BooleanField(default=False)),
                ('hidden_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('groups', models.ManyToManyField(related_name='custom_user_groups', to='auth.group')),
                ('role', models.ForeignKey(choices=[(1, 'Administrador'), (2, 'Abogado'), (3, 'Supervisor'), (4, 'Auxiliar')], default='', on_delete=django.db.models.deletion.CASCADE, to='users.role')),
                ('user_permissions', models.ManyToManyField(related_name='custom_user_permissions', to='auth.permission')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'user',
                'ordering': ('id',),
            },
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='loginregister',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
