# Generated by Django 4.2.10 on 2024-03-04 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='user_administrator',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
