# Generated by Django 4.2.10 on 2024-03-05 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(choices=[(1, 'Administrador'), (2, 'Abogado'), (3, 'Supervisor'), (4, 'Auxiliar')], default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.role'),
        ),
    ]
